[tool.bumpversion]
current_version = "1.4.0"
commit = true
tag = true
tag_name = "{new_major}.{new_minor}.{new_patch}"

[[tool.bumpversion.files]]
filename = "CMakeLists.txt"
search =  "project (occ_gordon VERSION {current_version})"
replace = "project (occ_gordon VERSION {new_version})"

[[tool.bumpversion.files]]
filename = "conda/meta.yaml"
search =  "set version = \"{current_version}\""
replace = "set version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "python/pyproject.toml"
search =  "version = \"{current_version}\""
replace = "version = \"{new_version}\""



